<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

	<ItemGroup>
		<None Update="Assets\Tutorial\*.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>
	
  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaXaml Remove="Views\Styles.axaml" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Views\Styles.axaml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="$(AvaloniaVersion)" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="$(AvaloniaVersion)" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="$(AvaloniaVersion)" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.0" />

    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
    <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" Version="$(AvaloniaVersion)" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Views\GameView.axaml.cs">
      <DependentUpon>GameView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\GameResultDialog.axaml.cs">
      <DependentUpon>GameResultDialog.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\MenuView.axaml.cs">
      <DependentUpon>MenuView.axaml</DependentUpon>
    </Compile>
  </ItemGroup>
</Project>
